#!/bin/sh

case "$1" in
    docker)
        docker build -t siem . && \
        docker run -it --rm \
            -e XDG_RUNTIME_DIR=/tmp \
            -v "$XDG_RUNTIME_DIR/wayland-1:/tmp/wayland-1" \
            -v "$(pwd)/siem.db:/app/siem.db" \
            siem
        ;;
    gcc)
        gcc main.c network/net_capture.c network/net_proto.c network/net_proto_tcp.c network/net_proto_udp.c db.c log.c \
        -Inetwork \
        $(pkg-config --cflags --libs gtk+-3.0) -lpcap -lsqlite3 -o siem \
        && sudo setcap cap_net_raw,cap_net_admin=eip siem \
        && ./siem
        ;;
    cmake)
        mkdir -p build && cd build && cmake .. && make -j"$(nproc)" && cd .. \
        && sudo setcap cap_net_raw,cap_net_admin=eip build/siem \
        && ./build/siem
    	;;
    make)
        make run
        ;;
    clear)
        rm -rf siem.db siem build log.o main.o db.o
        ;;
    *)
        echo "Usage: run {docker|gcc|cmake|make|clear}"
        exit 1
        ;;
esac