name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt install -y libgtk-3-dev

      - name: Build
        run: gcc -o siem main.c log.c $(pkg-config --cflags --libs gtk+-3.0) -Wall
